name: toxic lover-v2 xmd
services:
  - name: toxic lover-v2 xmd-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
